import { GroupOption } from '../types';

// eslint-disable-next-line import/prefer-default-export
export const FREQUENCIES: GroupOption[] = [
  {
    status: 'good',
    data: [
      {
        label: 'once every 5 minutes',
        value: 'once-every-five-minutes',
        simpleFrequency: 'Y',
        description: 'every 5 minutes',
      },
      {
        label: 'once every 10 minutes',
        value: 'once-every-ten-minutes',
        simpleFrequency: 'Y',
        description: 'every 10 minutes',
      },
      {
        label: 'once every 15 minutes',
        value: 'once-every-fifteen-minutes',
        simpleFrequency: 'Y',
        description: 'every 15 minutes',
      },
      {
        label: 'once every 30 minutes',
        value: 'once-every-thirty-minutes',
        simpleFrequency: 'Y',
        description: 'every 30 minutes',
      },
      {
        label: 'once every hour',
        value: 'once-every-hour',
        simpleFrequency: 'Y',
        description: 'every hour',
      },
      {
        label: 'once every 2 hours',
        value: 'once-every-two-hour',
        simpleFrequency: 'Y',
        description: 'every 2 hours',
      },
      {
        label: 'once every 3 hours',
        value: 'once-every-three-hour',
        simpleFrequency: 'Y',
        description: 'every 3 hours',
      },
      {
        label: 'once every 4 hours',
        value: 'once-every-four-hour',
        simpleFrequency: 'Y',
        description: 'every 4 hours',
      },
      {
        label: 'once every 5 hours',
        value: 'once-every-five-hour',
        simpleFrequency: 'Y',
        description: 'every 5 hours',
      },
      {
        label: 'once every 6 hours',
        value: 'once-every-six-hour',
        simpleFrequency: 'Y',
        description: 'every 6 hours',
      },
      {
        label: 'once every 7 hours',
        value: 'once-every-six-hour',
        simpleFrequency: 'Y',
        description: 'every 7 hours',
      },
      {
        label: 'once every 8 hours',
        value: 'once-every-eight-hour',
        simpleFrequency: 'Y',
        description: 'every 8 hours',
      },
      {
        label: 'once every 9 hours',
        value: 'once-every-nine-hour',
        simpleFrequency: 'Y',
        description: 'every 9 hours',
      },
      {
        label: 'once every 10 hours',
        value: 'once-every-ten-hour',
        simpleFrequency: 'Y',
        description: 'every 10 hours',
      },
      {
        label: 'once every 11 hours',
        value: 'once-every-eleven-hour',
        simpleFrequency: 'Y',
        description: 'every 11 hours',
      },
      {
        label: 'once every 12 hours',
        value: 'once-every-twelve-hour',
        simpleFrequency: 'Y',
        description: 'every 12 hours',
      },
      {
        label: 'once every 13 hours',
        value: 'once-every-thirteen-hour',
        simpleFrequency: 'Y',
        description: 'every 13 hours',
      },
      {
        label: 'once every 14 hours',
        value: 'once-every-fourteen-hour',
        simpleFrequency: 'Y',
        description: 'every 14 hours',
      },
      {
        label: 'once every 15 hours',
        value: 'once-every-fifteen-hour',
        simpleFrequency: 'Y',
        description: 'every 15 hours',
      },
      {
        label: 'once every 16 hours',
        value: 'once-every-sixteen-hour',
        simpleFrequency: 'Y',
        description: 'every 16 hours',
      },
      {
        label: 'once every 17 hours',
        value: 'once-every-seventeen-hour',
        simpleFrequency: 'Y',
        description: 'every 17 hours',
      },
      {
        label: 'once every 18 hours',
        value: 'once-every-eighteen-hour',
        simpleFrequency: 'Y',
        description: 'every 18 hours',
      },
      {
        label: 'once every 19 hours',
        value: 'once-every-nineteen-hour',
        simpleFrequency: 'Y',
        description: 'every 19 hours',
      },
      {
        label: 'once every 20 hours',
        value: 'once-every-twenty-hour',
        simpleFrequency: 'Y',
        description: 'every 20 hours',
      },
      {
        label: 'once every 21 hours',
        value: 'once-every-twenty-one-hour',
        simpleFrequency: 'Y',
        description: 'every 21 hours',
      },
      {
        label: 'once every 22 hours',
        value: 'once-every-twenty-two-hour',
        simpleFrequency: 'Y',
        description: 'every 22 hours',
      },
      {
        label: 'once every 23 hours',
        value: 'once-every-twenty-three-hour',
        simpleFrequency: 'Y',
        description: 'every 23 hours',
      },
      {
        label: 'once every 24 hours',
        value: 'once-every-twenty-four-hour',
        simpleFrequency: 'Y',
        description: 'every 24 hours',
      },
      {
        label: 'once every 36 hours',
        value: 'once-every-thirty-six-hour',
        simpleFrequency: 'Y',
        description: 'every 36 hours',
      },
      {
        label: 'once every 48 hours',
        value: 'once-every-forty-eight-hour',
        simpleFrequency: 'Y',
        description: 'every 48 hours',
      },
      {
        label: 'once every 72 hours',
        value: 'once-every-seventy-two-hour',
        simpleFrequency: 'Y',
        description: 'every 72 hours',
      },
      {
        label: 'once every 96 hours',
        value: 'once-every-ninety-six-hour',
        simpleFrequency: 'Y',
        description: 'every 96 hours',
      },
      {
        label: 'over 24 hours',
        value: 'over-twenty-four-hours',
        description: 'over 24 hours',
      },
      {
        label: 'over 48 hours',
        value: 'over-forty-eight-hours',
        description: 'over 48 hours',
      },
      {
        label: 'over 72 hours',
        value: 'over-seventy-two-hours',
        description: 'over 72 hours',
      },
      {
        label: 'over 96 hours',
        value: 'over-ninety-six-hours',
        description: 'over 96 hours',
      },
      {
        label: 'over 120 hours',
        value: 'over-one-hundred-twenty-hours',
        description: 'over 120 hours',
      },
      {
        label: 'once every 2 days',
        value: 'once-every-two-days',
        simpleFrequency: 'Y',
        description: 'every other day',
      },
      {
        label: 'once every 3 days',
        value: 'once-every-three-days',
        simpleFrequency: 'Y',
        description: 'every 3 days',
      },
      {
        label: 'once every 4 days',
        value: 'once-every-four-days',
        simpleFrequency: 'Y',
        description: 'every 4 days',
      },
      {
        label: 'once every 5 days',
        value: 'once-every-five-days',
        simpleFrequency: 'Y',
        description: 'every 5 days',
      },
      {
        label: 'once every 10 days',
        value: 'once-every-ten-days',
        simpleFrequency: 'Y',
        description: 'every 10 days',
      },
      {
        label: 'once every 11 days',
        value: 'once-every-eleven-days',
        simpleFrequency: 'Y',
        description: 'every 11 days',
      },
      {
        label: 'once every 14 days',
        value: 'once-every-fourteen-days',
        simpleFrequency: 'Y',
        description: 'every 14 days',
      },
      {
        label: 'once every 21 days',
        value: 'once-twenty-one-days',
        simpleFrequency: 'Y',
        description: 'every 21 days',
      },
      {
        label: 'once every 28 days',
        value: 'once-twenty-eight-days',
        simpleFrequency: 'Y',
        description: 'every 28 days',
      },
      {
        label: 'once every 30 days',
        value: 'once-every-thirty-days',
        simpleFrequency: 'Y',
        description: 'every 30 days',
      },
      {
        label: 'once every 60 days',
        value: 'once-every-sixty-days',
        simpleFrequency: 'Y',
        description: 'every 60 days',
      },
      {
        label: 'once every 90 days',
        value: 'once-every-ninety-days',
        simpleFrequency: 'Y',
        description: 'every 90 days',
      },
      {
        label: 'once every 120 days',
        value: 'once-every-one-hundred-twenty-days',

        simpleFrequency: 'Y',
        description: 'every 120 days',
      },
      {
        label: 'once every 180 days',
        value: 'once-every-one-hundred-eighty-days',
        simpleFrequency: 'Y',
        description: 'every 180 days',
      },
      {
        label: 'once every 5 weeks',
        value: 'once-every-five-weeks',
        simpleFrequency: 'Y',
        description: 'every 5 weeks',
      },
      {
        label: 'once every 6 weeks',
        value: 'once-every-six-weeks',
        simpleFrequency: 'Y',
        description: 'every 6 weeks',
      },
      {
        label: 'once every 7 weeks',
        value: 'once-every-seven-weeks',
        simpleFrequency: 'Y',
        description: 'every 7 weeks',
      },
      {
        label: 'once every 8 weeks',
        value: 'once-every-eight-weeks',
        simpleFrequency: 'Y',
        description: 'every 8 weeks',
      },
      {
        label: 'once every 9 weeks',
        value: 'once-every-nine-weeks',
        simpleFrequency: 'Y',
        description: 'every 9 weeks',
      },
      {
        label: 'once every 10 weeks',
        value: 'once-every-ten-weeks',
        simpleFrequency: 'Y',
        description: 'every 10 weeks',
      },
      {
        label: 'once every 11 weeks',
        value: 'once-every-eleven-weeks',
        simpleFrequency: 'Y',
        description: 'every 11 weeks',
      },
      {
        label: 'once every 12 weeks',
        value: 'once-every-twelve-weeks',
        simpleFrequency: 'Y',
        description: 'every 12 weeks',
      },
      {
        label: 'once every 14 weeks',
        value: 'once-every-fourteen-weeks',
        simpleFrequency: 'Y',
        description: 'every 14 weeks',
      },
      {
        label: 'once every 24 weeks',
        value: 'once-every-twenty-four-weeks',
        simpleFrequency: 'Y',
        description: 'every 24 weeks',
      },
      {
        label: 'once every 2 months',
        value: 'once-every-two-months',
        simpleFrequency: 'Y',
        description: 'every 2 months',
      },
      {
        label: 'once every 3 months',
        value: 'once-every-three-months',
        simpleFrequency: 'Y',
        description: 'every 3 months',
      },
      {
        label: 'once every 4 months',
        value: 'once-every-four-months',
        simpleFrequency: 'Y',
        description: 'every 4 months',
      },
      {
        label: 'once every 6 months',
        value: 'once-every-six-months',
        simpleFrequency: 'Y',
        description: 'every 6 months',
      },
      {
        label: 'once a year',
        value: 'once-a-year',
        simpleFrequency: 'Y',
        description: 'once a year',
      },
      {
        label: '2 times a year',
        value: 'two-times-a-year',
        simpleFrequency: 'Y',
        description: '2 times a year',
      },
      {
        label: '3 times a year',
        value: 'three-times-a-year',
        simpleFrequency: 'Y',
        description: '3 times a year',
      },
      {
        label: '4 times a year',
        value: 'four-times-a-year',
        simpleFrequency: 'Y',
        description: '4 times a year',
      },
      {
        label: 'once a day',
        value: 'once-a-day',
        simpleFrequency: 'Y',
        description: 'once a day',
      },
      {
        label: '2 times a day',
        value: 'two-times-a-day',
        simpleFrequency: 'Y',
        description: '2 times a day',
      },
      {
        label: '3 times a day',
        value: 'three-times-a-day',
        simpleFrequency: 'Y',
        description: '3 times a day',
      },
      {
        label: '4 times a day',
        value: 'four-times-a-day',
        simpleFrequency: 'Y',
        description: '4 times a day',
      },
      {
        label: '5 times a day',
        value: 'five-times-a-day',
        simpleFrequency: 'Y',
        description: '5 times a day',
      },
      {
        label: '6 times a day',
        value: 'six-times-a-day',
        simpleFrequency: 'Y',
        description: '6 times a day',
      },
      {
        label: '7 times a day',
        value: 'seven-times-a-day',
        simpleFrequency: 'Y',
        description: '7 times a day',
      },
      {
        label: '8 times a day',
        value: 'eight-times-a-day',
        simpleFrequency: 'Y',
        description: '8 times a day',
      },
      {
        label: '9 times a day',
        value: 'nine-times-a-day',
        simpleFrequency: 'Y',
        description: '9 times a day',
      },
      {
        label: '10 times a day',
        value: 'ten-times-a-day',
        simpleFrequency: 'Y',
        description: '10 times a day',
      },
      {
        label: 'once a day in the morning',
        value: 'once-a-day-in-the-morning',
        description: 'every morning',
      },
      {
        label: 'once a day in the afternoon',
        value: 'once-a-day-in-the-afternoon',
        description: 'every afternoon',
      },
      {
        label: 'once a day in the evening',
        value: 'once-a-day-in-the-evening',
        description: 'every evening',
      },
      {
        label: 'once a day at night',
        value: 'once-a-day-in-the-night',
        description: 'every night',
      },
      {
        label: 'once a day at bedtime',
        value: 'once-a-day-in-the-bedtime',
        description: 'at bedtime',
      },
      {
        label: 'once a week',
        value: 'once-a-week',
        simpleFrequency: 'Y',
        description: 'once a week',
      },
      {
        label: '2 times a week',
        value: 'two-times-a-week',
        simpleFrequency: 'Y',
        description: '2 times a week',
      },
      {
        label: '3 times a week',
        value: 'three-times-a-week',
        simpleFrequency: 'Y',
        description: '3 times a week',
      },
      {
        label: '4 times a week',
        value: 'four-times-a-week',
        simpleFrequency: 'Y',
        description: '4 times a week',
      },
      {
        label: '5 times a week',
        value: 'five-times-a-week',
        simpleFrequency: 'Y',
        description: '5 times a week',
      },
      {
        label: '6 times a week',
        value: 'six-times-a-week',
        simpleFrequency: 'Y',
        description: '6 times a week',
      },
      {
        label: '2 times a week on Monday and Thursday',
        value: 'two-times-a-week-on-monday-and-thursday',
        description: '2 times a week on Monday and Thursday',
      },
      {
        label: '2 times a week on Wednesday and Saturday',
        value: 'two-times-a-week-on-wednesday-and-saturday',
        description: '2 times a week on Wednesday and Saturday',
      },
      {
        label: '3 times a week on Monday, Wednesday and Friday',
        value: 'three-times-a-week-on-monday-and-wednesday-and-friday',
        description: '3 times a week on Monday, Wednesday and Friday',
      },
      {
        label: '3 times a week on Tuesday, Thursday and Saturday',
        value: 'three-times-a-week-on-tuesday-thursday-and-saturday',
        description: '3 times a week on Tuesday, Thursday and Saturday',
      },
      {
        label: '2 times a day for 2 days a week',
        value: 'two-times-a-day-for-two-days-a-week',
        simpleFrequency: 'Y',
        description: '2 times a day for 2 days a week',
      },
      {
        label: '2 times a day for 3 days a week',
        value: 'two-times-a-day-for-three-days-a-week',
        simpleFrequency: 'Y',
        description: '2 times a day for 3 days a week',
      },
      {
        label: '2 times a day for 4 days a week',
        value: 'two-times-a-day-for-four-days-a-week',
        simpleFrequency: 'Y',
        description: '2 times a day for 4 days a week',
      },
      {
        label: '2 times a day for 5 days a week',
        value: 'two-times-a-day-for-five-days-a-week',
        simpleFrequency: 'Y',
        description: '2 times a day for 5 days a week',
      },
      {
        label: '3 times a day for 2 days a week',
        value: 'three-times-a-day-for-two-days-a-week',
        simpleFrequency: 'Y',
        description: '3 times a day for 2 days a week',
      },
      {
        label: '3 times a day for 3 days a week',
        value: 'three-times-a-day-for-three-days-a-week',
        simpleFrequency: 'Y',
        description: '3 times a day for 3 days a week',
      },
      {
        label: '3 times a day for 4 days a week',
        value: 'three-times-a-day-for-four-days-a-week',
        simpleFrequency: 'Y',
        description: '3 times a day for 4 days a week',
      },
      {
        label: '3 times a day for 5 days a week',
        value: 'three-times-a-day-for-five-days-a-week',
        simpleFrequency: 'Y',
        description: '3 times a day for 5 days a week',
      },
      {
        label: 'once a month',
        value: 'once-a-month',
        simpleFrequency: 'Y',
        description: 'once a month',
      },
      {
        label: '2 times a month',
        value: 'two-times-a-month',
        simpleFrequency: 'Y',
        description: '2 times a month',
      },
      {
        label: '3 times a month',
        value: 'three-times-a-month',
        simpleFrequency: 'Y',
        description: '3 times a month',
      },
      {
        label: '4 times a month',
        value: 'four-times-a-month',
        simpleFrequency: 'Y',
        description: '4 times a month',
      },
      {
        label: 'once every minute for 5 times an hour',
        value: 'once-every-minute-for-five-times-an-hour',
        simpleFrequency: 'Y',
        description: 'every minute for 5 times an hour',
      },
    ],
  },
  {
    status: 'bad',
    data: [
      {
        label: '2 times a day in the morning and afternoon',
        value: 'two-times-a-day-in-the-morning-and-afternoon',
        description: '2 times a day in the morning and afternoon',
      },
      {
        label: '2 times a day in the afternoon and night',
        value: 'two-times-a-day-in-the-afternoon-and-night',
        description: '2 times a day in the afternoon and night',
      },
      {
        label: '2 times a day in the morning and night',
        value: 'two-times-a-day-in-the-morning-and-night',
        description: '2 times a day in the morning and night',
      },
      {
        label: '3 times a day in the morning, afternoon and night',
        value: 'three-times-a-day-in-the-morning-afternoon-and-night',
        description: '3 times a day in the morning, afternoon and night',
      },
      {
        label: '3 times a day and once a day at bedtime',
        value: 'three-times-a-day-and-once-a-day-at-bedtime',
        description: '3 times a day and at bedtime',
      },
      {
        label: 'once every 2 days in the afternoon',
        value: 'once-every-two-days-in-the-afternoon',
        description: 'every other afternoon',
      },
      {
        label: 'once every 2 days in the evening',
        value: 'once-every-two-days-in-the-evening',
        description: 'every other evening',
      },
      {
        label: 'once every 2 days at night',
        value: 'once-every-two-days-in-the-night',
        description: 'every other night',
      },
      {
        label: 'once every 2 days in the morning',
        value: 'once-every-two-days-in-the-morning',
        description: 'every other morning',
      },
      {
        label: 'once every 3 days in the morning',
        value: 'once-every-three-days-in-the-morning',
        description: 'every third morning',
      },
      {
        label: 'once a week in the morning on Monday',
        value: 'once-a-week-in-the-morning-on-monday',
        description: 'every Monday morning',
      },
      {
        label: 'once a week in the morning on Tuesday',
        value: 'once-a-week-in-the-morning-on-tuesday',
        description: 'every Tuesday morning',
      },
      {
        label: 'once a week in the morning on Wednesday',
        value: 'once-a-week-in-the-morning-on-wednesday',
        description: 'every Wednesday morning',
      },
      {
        label: 'once a week in the morning on Thursday',
        value: 'once-a-week-in-the-morning-on-thursday',
        description: 'every Thursday morning',
      },
      {
        label: 'once a week in the morning on Friday',
        value: 'once-a-week-in-the-morning-on-friday',
        description: 'every Friday morning',
      },
      {
        label: 'once a week in the morning on Saturday',
        value: 'once-a-week-in-the-morning-on-saturday',
        description: 'every Saturday morning',
      },
      {
        label: 'once a week in the morning on Sunday',
        value: 'once-a-week-in-the-morning-on-sunday',
        description: 'every Sunday morning',
      },
      {
        label: 'once in the morning for 6 days a week from Monday to Saturday',
        value: 'once-in-the-morning-for-six-days-a-week-from-monday-to-saturday',
        description: 'in the morning from Monday to Saturday',
      },
      {
        label: 'once in the morning for 5 days a week from Monday to Friday',
        value: 'once-in-the-morning-for-five-days-a-week-from-monday-to-friday',
        description: 'in the morning from Monday to Friday',
      },
      {
        label: 'once in the morning for 5 days a week on Monday, Tuesday, Thursday, Friday and Sunday',
        value: 'once-in-the-morning-for-five-days-a-week-on-monday-tuesday-thursday-friday-and-sunday',
        description: 'in the morning on Monday, Tuesday, Thursday, Friday and Sunday',
      },
      {
        label: 'once in the morning for 5 days a week on Monday, Wednesday, Friday, Saturday and Sunday',
        value: 'once-in-the-morning-for-five-days-a-week-on-monday-wednesday-friday-saturday-and-sunday',
        description: 'in the morning on Monday, Wednesday, Friday, Saturday and Sunday',
      },
      {
        label: 'once in the morning for 5 days a week on Tuesday, Wednesday, Friday, Saturday and Sunday',
        value: 'once-in-the-morning-for-five-days-a-week-on-tuesday-wednesday-friday-saturday-and-sunday',
        description: 'in the morning on Tuesday, Wednesday, Friday, Saturday and Sunday',
      },
      {
        label: 'once in the morning for 4 days a week from Monday to Thursday',
        value: 'once-in-the-morning-for-four-days-a-week-from-monday-to-thursday',
        description: 'in the morning from Monday to Thursday',
      },
      {
        label: 'once in the morning for 4 days a week on Monday, Wednesday, Friday and Sunday',
        value: 'once-in-the-morning-for-four-days-a-week-from-monday-to-thursday',
        description: 'in the morning on Monday, Wednesday, Friday and Sunday',
      },
      {
        label: 'once in the morning for 4 days a week on Tuesday, Thursday, Saturday and Sunday',
        value: 'once-in-the-morning-for-four-days-a-week-on-tuesday-thursday-saturday-and-sunday',
        description: 'in the morning on Tuesday, Thursday, Saturday and Sunday',
      },
      {
        label: 'once in the morning for 4 days a week from Thursday to Sunday',
        value: 'once-in-the-morning-for-four-days-a-week-from-thursday-to-sunday',
        description: 'in the morning from Thursday to Sunday',
      },
      {
        label: 'once in the morning for 3 days a week from Monday to Wednesday',
        value: 'once-in-the-morning-for-three-days-a-week-from-monday-to-wednesday',
        description: 'in the morning from Monday to Wednesday',
      },
      {
        label: 'once in the morning for 3 days a week on Monday, Wednesday and Friday',
        value: 'once-in-the-morning-for-three-days-a-week-on-monday-wednesday-and-friday',
        description: 'in the morning on Monday, Wednesday and Friday',
      },
      {
        label: 'once in the morning for 3 days a week on Tuesday, Thursday and Saturday',
        value: 'once-in-the-morning-for-three-days-a-week-on-tuesday-thursday-and-saturday',
        description: 'in the morning on Tuesday, Thursday and Saturday',
      },
      {
        label: 'once in the morning for 3 days a week from Friday to Sunday',
        value: 'once-in-the-morning-for-three-days-a-week-on-tuesday-thursday-and-saturday',
        description: 'in the morning from Friday to Sunday',
      },
      {
        label: 'once in the morning for 2 days a week on Monday and Thursday',
        value: 'once-in-the-morning-for-two-days-a-week-on-monday-and-thursday',
        description: 'in the morning on Monday and Thursday',
      },
      {
        label: 'once in the morning for 2 days a week on Tuesday and Thursday',
        value: 'once-in-the-morning-for-two-days-a-week-on-tuesday-and-thursday',
        description: 'in the morning on Tuesday and Thursday',
      },
      {
        label: 'once in the morning for 2 days a week on Wednesday and Saturday',
        value: 'once-in-the-morning-for-two-days-a-week-on-wednesday-and-saturday',
        description: 'in the morning on Wednesday and Saturday',
      },
      {
        label: 'once in the morning for 2 days a week on Saturday and Sunday',
        value: 'once-in-the-morning-for-two-days-a-week-on-saturday-and-sunday',
        description: 'in the morning on Saturday and Sunday',
      },
      {
        label: 'once at night for 6 days a week from Monday to Saturday',
        value: 'once-at-night-for-six-days-a-week-from-monday-to-saturday',
        description: 'at night from Monday to Saturday',
      },
      {
        label: 'once at night for 5 days a week from Monday to Friday',
        value: 'once-at-night-for-five-days-a-week-from-monday-to-friday',
        description: 'at night from Monday to Friday',
      },
      {
        label: 'once at night for 5 days a week on Monday, Tuesday, Thursday, Friday and Sunday',
        value: 'once-at-night-for-five-days-a-week-on-monday-tuesday-thursday-friday-and-sunday',
        description: 'at night on Monday, Tuesday, Thursday, Friday and Sunday',
      },
      {
        label: 'once at night for 5 days a week on Monday, Wednesday, Friday, Saturday and Sunday',
        value: 'once-at-night-for-five-days-a-week-on-monday-wednesday-friday-saturday-and-sunday',
        description: 'at night on Monday, Wednesday, Friday, Saturday and Sunday',
      },
      {
        label: 'once at night for 5 days a week on Tuesday, Wednesday, Friday, Saturday and Sunday',
        value: 'once-at-night-for-five-days-a-week-on-tuesday-wednesday-friday-saturday-and-sunday',
        description: 'at night on Tuesday, Wednesday, Friday, Saturday and Sunday',
      },
      {
        label: 'once at night for 4 days a week from Monday to Thursday',
        value: 'once-at-night-for-four-days-a-week-from-monday-to-thursday',
        description: 'at night from Monday to Thursday',
      },
      {
        label: 'once at night for 4 days a week on Monday, Wednesday, Friday and Sunday',
        value: 'once-at-night-for-four-days-a-week-on-monday-wednesday-friday-and-sunday',
        description: 'at night on Monday,Wednesday, Friday and Sunday',
      },
      {
        label: 'once at night for 4 days a week on Tuesday, Thursday, Saturday and Sunday',
        value: 'once-at-night-for-four-days-a-week-on-tuesday-thursday-saturday-and-sunday',
        description: 'at night on Tuesday, Thursday, Saturday and Sunday',
      },
      {
        label: 'once at night for 4 days a week from Thursday to Sunday',
        value: 'once-at-night-for-four-days-a-week-from-thursday-to-sunday',
        description: 'at night from Thursday to Sunday',
      },
      {
        label: 'once at night for 3 days a week from Monday to Wednesday',
        value: 'once-at-night-for-three-days-a-week-from-monday-to-wednesday',
        description: 'at night from Monday to Wednesday',
      },
      {
        label: 'once at night for 3 days a week on Monday, Wednesday and Friday',
        value: 'once-at-night-for-three-days-a-week-on-monday-wednesday-and-friday',
        description: 'at night on Monday, Wednesday and Friday',
      },
      {
        label: 'once at night for 3 days a week on Tuesday, Thursday and Saturday',
        value: 'once-at-night-for-three-days-a-week-on-tuesday-thursday-and-saturday',
        description: 'at night on Tuesday, Thursday and Saturday',
      },
      {
        label: 'once at night for 3 days a week from Friday to Sunday',
        value: 'once-at-night-for-three-days-a-week-from-friday-to-sunday',
        description: 'at night from Friday to Sunday',
      },
      {
        label: 'once at night for 2 days a week on Monday and Thursday',
        value: 'once-at-night-for-two-days-a-week-on-monday-and-thursday',
        description: 'at night on Monday and Thursday',
      },
      {
        label: 'once at night for 2 days a week on Tuesday and Thursday',
        value: 'once-at-night-for-two-days-a-week-on-tuesday-and-thursday',
        description: 'at night on Tuesday and Thursday',
      },
      {
        label: 'once at night for 2 days a week on Wednesday and Saturday',
        value: 'once-at-night-for-two-days-a-week-on-wednesday-and-saturday',
        description: 'at night on Wednesday and Saturday',
      },
      {
        label: 'once at night for 2 days a week on Saturday and Sunday',
        value: 'once-at-night-for-two-days-a-week-on-saturday-and-sunday',
        description: 'at night on Saturday and Sunday',
      },
      {
        label: 'once a week at night on Monday',
        value: 'once-a-week-at-night-on-monday',
        description: 'every Monday night',
      },
      {
        label: 'once a week at night on Tuesday',
        value: 'once-a-week-at-night-on-monday',
        description: 'every Tuesday night',
      },
      {
        label: 'once a week at night on Wednesday',
        value: 'once-a-week-at-night-on-wednesday',
        description: 'every Wednesday night',
      },
      {
        label: 'once a week at night on Thursday',
        value: 'once-a-week-at-night-on-thursday',
        description: 'every Thursday night',
      },
      {
        label: 'once a week at night on Friday',
        value: 'once-a-week-at-night-on-friday',
        description: 'every Friday night',
      },
      {
        label: 'once a week at night on Saturday',
        value: 'once-a-week-at-night-on-saturday',
        description: 'every Saturday night',
      },
      {
        label: 'once a week at night on Sunday',
        value: 'once-a-week-at-night-on-sunday',
        description: 'every Sunday night',
      },
      {
        label: 'once a day at 12:00am',
        value: 'once-a-day-at-twelve-am',
        description: 'once a day at 12am',
      },
      {
        label: 'once a day at 1:00am',
        value: 'once-a-day-at-one-am',
        description: 'once a day at 1am',
      },
      {
        label: 'once a day at 2:00am',
        value: 'once-a-day-at-two-am',
        description: 'once a day at 2am',
      },
      {
        label: 'once a day at 3:00am',
        value: 'once-a-day-at-three-am',
        description: 'once a day at 3am',
      },
      {
        label: 'once a day at 4:00am',
        value: 'once-a-day-at-four-am',
        description: 'once a day at 4am',
      },
      {
        label: 'once a day at 5:00am',
        value: 'once-a-day-at-five-am',
        description: 'once a day at 5am',
      },
      {
        label: 'once a day at 6:00am',
        value: 'once-a-day-at-six-am',
        description: 'once a day at 6am',
      },
      {
        label: 'once a day at 7:00am',
        value: 'once-a-day-at-seven-am',
        description: 'once a day at 7am',
      },
      {
        label: 'once a day at 8:00am',
        value: 'once-a-day-at-eight-am',
        description: 'once a day at 8am',
      },
      {
        label: 'once a day at 9:00am',
        value: 'once-a-day-at-nine-am',
        description: 'once a day at 9am',
      },
      {
        label: 'once a day at 10:00am',
        value: 'once-a-day-at-ten-am',
        description: 'once a day at 10am',
      },
      {
        label: 'once a day at 11:00am',
        value: 'once-a-day-at-eleven-am',
        description: 'once a day at 11am',
      },
      {
        label: 'once a day at 12:00pm',
        value: 'once-a-day-at-twelve-pm',
        description: 'once a day at 12pm',
      },
      {
        label: 'once a day at 1:00pm',
        value: 'once-a-day-at-one-pm',
        description: 'once a day at 1pm',
      },
      {
        label: 'once a day at 2:00pm',
        value: 'once-a-day-at-two-pm',
        description: 'once a day at 2pm',
      },
      {
        label: 'once a day at 3:00pm',
        value: 'once-a-day-at-three-pm',
        description: 'once a day at 3pm',
      },
      {
        label: 'once a day at 4:00pm',
        value: 'once-a-day-at-four-pm',
        description: 'once a day at 4pm',
      },
      {
        label: 'once a day at 5:00pm',
        value: 'once-a-day-at-five-pm',
        description: 'once a day at 5pm',
      },
      {
        label: 'once a day at 6:00pm',
        value: 'once-a-day-at-six-pm',
        description: 'once a day at 6pm',
      },
      {
        label: 'once a day at 8:00pm',
        value: 'once-a-day-at-eight-pm',
        description: 'once a day at 8pm',
      },
      {
        label: 'once a day at 7:00pm',
        value: 'once-a-day-at-seven-pm',
        description: 'once a day at 7pm',
      },
      {
        label: 'once a day at 9:00pm',
        value: 'once-a-day-at-nine-pm',
        description: 'once a day at 9pm',
      },
      {
        label: 'once a day at 10:00pm',
        value: 'once-a-day-at-ten-pm',
        description: 'once a day at 10pm',
      },
      {
        label: 'once a day at 11:00pm',
        value: 'once-a-day-at-eleven-pm',
        description: 'once a day at 11pm',
      },
      {
        label: '2 times a day at 7:00am and 5:30pm',
        value: 'two-times-a-day-at-seven-am-and-five-thirty-pm',
        description: '2 times a day at 7am and 5:30pm',
      },
      {
        label: '2 times a day at 7:00am and 6:00pm',
        value: 'two-times-a-day-at-seven-am-and-six-pm',
        description: '2 times a day at 7am and 6pm',
      },
      {
        label: '2 times a day at 8:00am and 2:00pm',
        value: 'two-times-a-day-at-eight-am-and-two-pm',
        description: '2 times a day at 8am and 2pm',
      },
      {
        label: '2 times a day at 8:00am and 4:00pm',
        value: 'two-times-a-day-at-eight-am-and-four-pm',
        description: '2 times a day at 8am and 4pm',
      },
      {
        label: '2 times a day at 8:00am and 5:00pm',
        value: 'two-times-a-day-at-eight-am-and-five-pm',
        description: '2 times a day at 8am and 5pm',
      },
      {
        label: '2 times a day at 10:00am and 3:00pm',
        value: 'two-times-a-day-at-ten-am-and-three-pm',
        description: '2 times a day at 10am and 3pm',
      },
      {
        label: '3 times a day at 7:00am, 11:30am and 5:30pm',
        value: 'three-times-a-day-at-seven-am-and-five-thirty-pm',
        description: '3 times a day at 7am, 11:30am and 5:30pm',
      },
      {
        label: '3 times a day at 7:00am, 1:00pm and 6:00pm',
        value: 'three-times-a-day-at-seven-am-one-pm-and-six-pm',
        description: '3 times a day at 7am, 1pm and 6pm',
      },
      {
        label: '3 times a day at 8:00am, 12:00pm and 4:00pm',
        value: 'three-times-a-day-at-eight-am-twelve-pm-and-four-pm',
        description: '3 times a day at 8am, 12pm and 4pm',
      },
      {
        label: '3 times a day at 8:00am, 1:00pm and 5:00pm',
        value: 'three-times-a-day-at-eight-am-one-pm-and-five-pm',
        description: '3 times a day at 8am, 1pm and 5pm',
      },
      {
        label: '3 times a day at 8:00am, 2:00pm and at bedtime',
        value: 'three-times-a-day-at-eight-am-two-pm-and-at-bedtime',
        description: '3 times a day at 8am, 2pm and at bedtime',
      },
      {
        label: '3 times a day at 9:00am, 3:00pm and 9:00pm',
        value: 'three-times-a-day-at-nine-am-three-pm-and-nine-pm',
        description: '3 times a day at 9am, 3pm and 9pm',
      },
      {
        label: '3 times a day at 10:00am, 3:00pm and 8:00pm',
        value: 'three-times-a-day-at-ten-am-three-pm-and-eight-pm',
        description: '3 times a day at 10am, 3pm and 8pm',
      },
      {
        label: '4 times a day at 7:00am, 11:00pm, 3:00pm and 7:00pm',
        value: 'four-times-a-day-at-seven-am-eleven-pm-three-pm-and-seven-pm',

        description: '4 times a day at 7am, 11pm, 3pm and 7pm',
      },
      {
        label: '4 times a day at 8:00am, 12:00pm, 4:00pm and 8:00pm',
        value: 'four-times-a-day-at-eight-am-twelve-pm-four-pm-and-eight-pm',
        description: '4 times a day at 8am, 12pm, 4pm and 8pm',
      },
      {
        label: '4 times a day at 8:00am, 1:00pm, 5:00pm and 10:00pm',
        value: 'four-times-a-day-at-eight-am-one-pm-five-pm-and-ten-pm',
        description: '4 times a day at 8am, 1pm, 5pm and 10pm',
      },
      {
        label: '4 times a day at 8:00am, 1:00pm, 8:00pm and 10:00pm',
        value: 'four-times-a-day-at-eight-am-one-pm-five-pm-and-ten-pm',
        description: '4 times a day at 8am, 1pm, 8pm and 10pm',
      },
      {
        label: '5 times a day at 7:00am, 10:00am, 1:00pm, 4:00pm and 7:00pm',
        value: 'five-times-a-day-at-seven-am-ten-am-one-pm-four-pm-and-seven-pm',
        description: '5 times a day at 7am, 10am, 1pm, 4pm and 7pm',
      },
      {
        label: '6 times a day at 7:00am, 10:00am, 1:00pm, 4:00pm, 7:00pm and 10:00pm',
        value: 'six-times-a-day-at-seven-am-ten-am-one-pm-four-pm-seven-pm-and-ten-pm',
        description: '6 times a day at 7am, 10am, 1pm, 4pm, 7pm and 10pm',
      },
      {
        label: '7 times a day at 7:00am, 9:00am, 11:00am, 1:00pm, 3:00pm, 5:00pm and 7:00pm',
        value: 'seven-times-a-day-at-seven-am-nine-am-eleven-am-one-pm-three-pm-five-pm-and-seven-pm',
        description: '7 times a day at 7am, 9am, 11am, 1pm, 3pm, 5pm and 7pm',
      },
      {
        label: 'once a week on Monday',
        value: 'once-a-week-on-monday',
        description: 'every Monday',
      },
      {
        label: 'once a week on Tuesday',
        value: 'once-a-week-on-tuesday',
        description: 'every Tuesday',
      },
      {
        label: 'once a week on Wednesday',
        value: 'once-a-week-on-wednesday',
        description: 'every Wednesday',
      },
      {
        label: 'once a week on Thursday',
        value: 'once-a-week-on-thursday',
        description: 'every Thursday',
      },
      {
        label: 'once a week on Friday',
        value: 'once-a-week-on-friday',
        description: 'every Friday',
      },
      {
        label: 'once a week on Saturday',
        value: 'once-a-week-on-saturday',
        description: 'every Saturday',
      },
      {
        label: 'once a week on Sunday',
        value: 'once-a-week-on-sunday',
        description: 'every Sunday',
      },
      {
        label: 'once a day for 2 days a week on Monday and Wednesday',
        value: 'once-a-day-for-two-days-a-week-on-monday-and-wednesday',
        description: 'once a day on Monday and Wednesday',
      },
      {
        label: 'once a day for 2 days a week on Monday and Friday',
        value: 'once-a-day-for-two-days-a-week-on-monday-and-friday',
        description: 'once a day on Monday and Friday',
      },
      {
        label: 'once a day for 2 days a week on Monday and Thursday',
        value: 'once-a-day-for-two-days-a-week-on-monday-and-thursday',
        description: 'once a day on Monday and Thursday',
      },
      {
        label: 'once a day for 2 days a week on Tuesday and Thursday',
        value: 'once-a-day-for-two-days-a-week-on-tuesday-and-thursday',
        description: 'once a day on Tuesday and Thursday',
      },
      {
        label: 'once a day for 2 days a week on Tuesday and Friday',
        value: 'once-a-day-for-two-days-a-week-on-tuesday-and-friday',
        description: 'once a day on Tuesday and Friday',
      },
      {
        label: 'once a day for 2 days a week on Wednesday and Friday',
        value: 'once-a-day-for-two-days-a-week-on-wednesday-and-friday',
        description: 'once a day on Wednesday and Friday',
      },
      {
        label: 'once a day for 2 days a week on Wednesday and Saturday',
        value: 'once-a-day-for-two-days-a-week-on-wednesday-and-saturday',
        description: 'once a day on Wednesday and Saturday',
      },
      {
        label: 'once a day for 2 days a week on Saturday and Sunday',
        value: 'once-a-day-for-two-days-a-week-on-saturday-and-sunday',
        description: 'once a day on Saturday and Sunday',
      },
      {
        label: 'once a day for 6 days a week from Monday to Saturday',
        value: 'once-a-day-for-six-days-a-week-from-monday-to-saturday',
        description: 'once a day from Monday to Saturday',
      },
      {
        label: 'once a day for 5 days a week from Monday to Friday',
        value: 'once-a-day-for-five-days-a-week-from-monday-to-friday',
        description: 'once a day from Monday to Friday',
      },
      {
        label: 'once a day for 5 days a week on Monday, Tuesday, Thursday, Friday and Sunday',
        value: 'once-a-day-for-five-days-a-week-from-monday-tuesday-thursday-friday-and-sunday',
        description: 'once a day on Monday, Tuesday, Thursday, Friday and Sunday',
      },
      {
        label: 'once a day for 5 days a week on Monday, Wednesday, Thursday, Saturday and Sunday',
        value: 'once-a-day-for-five-days-a-week-on-monday-wednesday-thursday-saturday-and-sunday',
        description: 'once a day on Monday, Wednesday, Thursday, Saturday and Sunday',
      },
      {
        label: 'once a day for 5 days a week on Monday, Wednesday, Friday, Saturday and Sunday',
        value: 'once-a-day-for-five-days-a-week-on-monday-wednesday-friday-saturday-and-sunday',
        description: 'once a day on Monday, Wednesday, Friday, Saturday and Sunday',
      },
      {
        label: 'once a day for 5 days a week on Tuesday, Wednesday, Friday, Saturday and Sunday',
        value: 'once-a-day-for-five-days-a-week-on-tuesday-wednesday-friday-saturday-and-sunday',
        description: 'once a day on Tuesday, Wednesday, Friday, Saturday and Sunday',
      },
      {
        label: 'once a day for 4 days a week from Monday to Thursday',
        value: 'once-a-day-for-four-days-a-week-from-monday-to-thursday',
        description: 'once a day from Monday to Thursday',
      },
      {
        label: 'once a day for 4 days a week on Monday, Wednesday, Friday and Sunday',
        value: 'once-a-day-for-four-days-a-week-on-monday-wednesday-friday-and-sunday',
        description: 'once a day on Monday, Wednesday, Friday and Sunday',
      },
      {
        label: 'once a day for 4 days a week on Tuesday, Thursday, Saturday and Sunday',
        value: 'once-a-day-for-four-days-a-week-on-monday-thursday-saturday-and-sunday',
        description: 'once a day on Tuesday, Thursday, Saturday and Sunday',
      },
      {
        label: 'once a day for 4 days a week from Thursday to Sunday',
        value: 'once-a-day-for-four-days-a-week-from-thursday-to-sunday',
        description: 'once a day from Thursday to Sunday',
      },
      {
        label: 'once a day for 3 days a week from Monday to Wednesday',
        value: 'once-a-day-for-three-days-a-week-from-monday-to-wednesday',
        description: 'once a day from Monday to Wednesday',
      },
      {
        label: 'once a day for 3 days a week on Monday, Wednesday and Friday',
        value: 'once-a-day-for-three-days-a-week-on-monday-wednesday-and-friday',
        description: 'once a day on Monday, Wednesday and Friday',
      },
      {
        label: 'once a day for 3 days a week on Tuesday, Thursday and Saturday',
        value: 'once-a-day-for-three-days-a-week-on-tuesday-thursday-and-saturday',
        description: 'once a day on Tuesday, Thursday and Saturday',
      },
      {
        label: 'once a day for 3 days a week from Friday to Sunday',
        value: 'once-a-day-for-three-days-a-week-from-friday-to-sunday',
        description: 'once a day from Friday to Sunday',
      },
      {
        label: '2 times a day on Monday',
        value: 'two-times-a-day-on-monday',
        description: '2 times a day on Monday',
      },
      {
        label: '2 times a day on Tuesday',
        value: 'two-times-a-day-on-tuesday',
        description: '2 times a day on Tuesday',
      },
      {
        label: '2 times a day on Wednesday',
        value: 'two-times-a-day-on-wednesday',
        description: '2 times a day on Wednesday',
      },
      {
        label: '2 times a day on Thursday',
        value: 'two-times-a-day-on-thursday',
        description: '2 times a day on Thursday',
      },
      {
        label: '2 times a day on Friday',
        value: 'two-times-a-day-on-friday',
        description: '2 times a day on Friday',
      },
      {
        label: '2 times a day on Saturday',
        value: 'two-times-a-day-on-saturday',
        description: '2 times a day on Saturday',
      },
      {
        label: '2 times a day on Sunday',
        value: 'two-times-a-day-on-sunday',
        description: '2 times a day on Sunday',
      },
      {
        label: '2 times a day for 3 days a week on Monday, Wednesday and Friday',
        value: 'two-times-a-day-for-three-days-a-week-on-monday-wednesday-and-friday',
        description: '2 times a day on Monday, Wednesday and Friday',
      },
      {
        label: '2 times a day for 2 days a week on Monday and Tuesday',
        value: 'two-times-a-day-for-two-days-a-week-on-monday-and-tuesday',
        description: '2 times a day on Monday and Tuesday',
      },
      {
        label: '2 times a day for 2 days a week on Monday and Thursday',
        value: 'two-times-a-day-for-two-days-a-week-on-monday-and-thursday',
        description: '2 times a day on Monday and Thursday',
      },
      {
        label: '2 times a day for 2 days a week on Thursday and Sunday',
        value: 'two-times-a-day-for-two-days-a-week-on-thursday-and-sunday',
        description: '2 times a day on Thursday and Sunday',
      },
      {
        label: '2 times a day for 2 days a week on Tuesday and Friday',
        value: 'two-times-a-day-for-two-days-a-week-on-tuesday-and-friday',
        description: '2 times a day on Tuesday and Friday',
      },
      {
        label: '2 times a day for 2 days a week on Wednesday and Saturday',
        value: 'two-times-a-day-for-two-days-a-week-on-wednesday-and-saturday',
        description: '2 times a day on Wednesday and Saturday',
      },
      {
        label: '2 times a day before food',
        value: 'two-times-a-day-before-food',
        description: '2 times a day before food',
      },
      {
        label: '3 times a day before food',
        value: 'three-times-a-day-before-food',
        description: '3 times a day before food',
      },
      {
        label: '4 times a day before food',
        value: 'four-times-a-day-before-food',
        description: '4 times a day before food',
      },
      {
        label: '2 times a day with food',
        value: 'two-times-a-day-with-food',
        description: '2 times a day with food',
      },
      {
        label: '3 times a day with food',
        value: 'three-times-a-day-with-food',
        description: '3 times a day with food',
      },
      {
        label: '4 times a day with food',
        value: 'four-times-a-day-with-food',
        description: '4 times a day with food',
      },
      {
        label: '2 times a day after food',
        value: 'two-times-a-day-after-food',
        description: '2 times a day after food',
      },
      {
        label: '3 times a day after food',
        value: 'three-times-a-day-after-food',
        description: '3 times a day after food',
      },
      {
        label: '4 times a day after food',
        value: 'four-times-a-day-after-food',
        description: '4 times a day after food',
      },
      {
        label: '2 times a day before food, omit if nil by mouth',
        value: 'two-times-a-day-before-food-omit-if-nil-by-mouth',
        description: '2 times a day before food, omit if nil by mouth',
      },
      {
        label: '3 times a day before food, omit if nil by mouth',
        value: 'three-times-a-day-before-food-omit-if-nil-by-mouth',
        description: '3 times a day before food, omit if nil by mouth',
      },
      {
        label: '4 times a day before breakfast, lunch and dinner and at bedtime',
        value: 'four-times-a-day-before-breakfast-lunch-and-dinner-and-at-bedtime',
        description: '4 times a day before breakfast, lunch and dinner and at bedtime',
      },
      {
        label: '5 times a day before breakfast, lunch and dinner and at bedtime and 2:00am',
        value: 'five-times-a-day-before-breakfast-lunch-and-dinner-and-at-bedtime-and-two-am',
        description: '5 times a day before breakfast, lunch and dinner and at bedtime and 2am',
      },
      {
        label: '2 times a day with food, omit if nil by mouth',
        value: 'two-times-a-day-with-food-omit-if-nil-by-mouth',
        description: '2 times a day with food, omit if nil by mouth',
      },
      {
        label: '3 times a day with food, omit if nil by mouth',
        value: 'three-times-a-day-with-food-omit-if-nil-by-mouth',
        description: '3 times a day with food, omit if nil by mouth',
      },
      {
        label: 'once a day before breakfast',
        value: 'once-a-day-before-breakfast',
        description: 'once a day before breakfast',
      },
      {
        label: 'once a day with breakfast',
        value: 'once-a-day-with-breakfast',
        description: 'once a day with breakfast',
      },
      {
        label: 'once a day after breakfast',
        value: 'once-a-day-after-breakfast',
        description: 'once a day after breakfast',
      },
      {
        label: 'once a day in the morning before food',
        value: 'once-a-day-in-the-morning-before-food',
        description: 'every morning before food',
      },
      {
        label: 'once a day in the morning with food',
        value: 'once-a-day-in-the-morning-with-food',
        description: 'every morning with food',
      },
      {
        label: 'once a day in the morning after food',
        value: 'once-a-day-in-the-morning-after-food',
        description: 'every morning after food',
      },
      {
        label: 'once a day before lunch',
        value: 'once-a-day-before-lunch',
        description: 'once a day before lunch',
      },
      {
        label: 'once a day with lunch',
        value: 'once-a-day-with-lunch',
        description: 'once a day with lunch',
      },
      {
        label: 'once a day after lunch',
        value: 'once-a-day-after-lunch',
        description: 'once a day after lunch',
      },
      {
        label: 'once a day in the afternoon before food',
        value: 'once-a-day-in-the-afternoon-before-food',
        description: 'every afternoon before food',
      },
      {
        label: 'once a day in the afternoon with food',
        value: 'once-a-day-in-the-afternoon-with-food',
        description: 'every afternoon with food',
      },
      {
        label: 'once a day in the afternoon after food',
        value: 'once-a-day-in-the-afternoon-after-food',
        description: 'every afternoon after food',
      },
      {
        label: 'once a day before dinner',
        value: 'once-a-day-before-dinner',
        description: 'once a day before dinner',
      },
      {
        label: 'once a day with dinner',
        value: 'once-a-day-with-dinner',
        description: 'once a day with dinner',
      },
      {
        label: 'once a day after dinner',
        value: 'once-a-day-after-dinner',
        description: 'once a day after dinner',
      },
      {
        label: 'once a day at night before food',
        value: 'once-a-day-at-night-before-food',
        description: 'every night before food',
      },
      {
        label: 'once a day at night with food',
        value: 'once-a-day-at-night-with-food',
        description: 'every night with food',
      },
      {
        label: 'once a day at night after food',
        value: 'once-a-day-at-night-after-food',
        description: 'every night after food',
      },
      {
        label: 'once a day before supper',
        value: 'once-a-day-before-supper',
        description: 'once a day before supper',
      },
      {
        label: '2 times a day before breakfast and dinner',
        value: 'two-times-a-day-before-breakfast-and-dinner',
        description: '2 times a day before breakfast and dinner',
      },
      {
        label: '2 times a day with breakfast and lunch',
        value: 'two-times-a-day-before-breakfast-and-lunch',
        description: '2 times a day with breakfast and lunch',
      },
      {
        label: 'once a day in the morning before food, omit if nil by mouth',
        value: 'once-a-day-in-the-morning-before-food-omit-if-nil-by-mouth',
        description: 'every morning before food, omit if nil by mouth',
      },
      {
        label: 'once a day in the morning with food, omit if nil by mouth',
        value: 'once-a-day-in-the-morning-with-food-omit-if-nil-by-mouth',
        description: 'every morning with food, omit if nil by mouth',
      },
      {
        label: 'once a day in the afternoon before food, omit if nil by mouth',
        value: 'once-a-day-in-the-afternoon-before-food-omit-if-nil-by-mouth',
        description: 'every afternoon before food, omit if nil by mouth',
      },
      {
        label: 'once a day in the afternoon with food, omit if nil by mouth',
        value: 'once-a-day-in-the-afternoon-with-food-omit-if-nil-by-mouth',
        description: 'every afternoon with food, omit if nil by mouth',
      },
      {
        label: 'once a day at night before food, omit if nil by mouth',
        value: 'once-a-day-at-night-before-food-omit-if-nil-by-mouth',
        description: 'every night before food, omit if nil by mouth',
      },
      {
        label: 'once a day at night with food, omit if nil by mouth',
        value: 'once-a-day-at-night-with-food-omit-if-nil-by-mouth',
        description: 'every night with food, omit if nil by mouth',
      },
      {
        label: 'once a week before food',
        value: 'once-a-week-before-food',
        description: 'once a week before food',
      },
      {
        label: 'once a day for 2 days a week before food',
        value: 'once-a-day-for-two-days-a-week-before-food',
        description: 'once a day for 2 days a week before food',
      },
      {
        label: 'once a day for 3 days a week before food',
        value: 'once-a-day-for-three-days-a-week-before-food',
        description: 'once a day for 3 days a week before food',
      },
      {
        label: 'once a day for 4 days a week before food',
        value: 'once-a-day-for-four-days-a-week-before-food',
        description: 'once a day for 4 days a week before food',
      },
      {
        label: 'once a day for 5 days a week before food',
        value: 'once-a-day-for-five-days-a-week-before-food',
        description: 'once a day for 5 days a week before food',
      },
      {
        label: 'once a day for 6 days a week before food',
        value: 'once-a-day-for-six-days-a-week-before-food',
        description: 'once a day for 6 days a week before food',
      },
      {
        label: 'once a month before food',
        value: 'once-a-month-before-food',
        description: 'once a month before food',
      },
      {
        label: 'once a month before food at 7:00am',
        value: 'once-a-month-before-food-at-seven-am',
        description: 'once a month before food at 7am',
      },
      {
        label: 'once every 30 days before food',
        value: 'once-every-thirty-days-before-food',
        description: 'every 30 days before food',
      },
      {
        label: 'stat',
        value: 'stat',
        description: 'stat',
      },
      {
        label: 'once',
        value: 'once',
        description: 'once',
      },
      {
        label: 'once at 8:00am',
        value: 'once-at-eight-am',
        description: 'once at 8am',
      },
      {
        label: 'once at 2:00pm',
        value: 'once-at-two-am',
        description: 'once at 2pm',
      },
      {
        label: 'once at 6:00pm',
        value: 'once-at-six-pm',
        description: 'once at 6pm',
      },
      {
        label: 'once every 2 to 6 hours',
        value: 'once-every-two-to-six-hours',
        description: 'every 2 to 6 hours',
      },
      {
        label: 'once every 4 to 6 hours',
        value: 'once-every-four-to-six-hours',
        description: 'every 4 to 6 hours',
      },
      {
        label: 'once a day for 10 days per 28-day cycle',
        value: 'once-a-day-for-ten-days-per-twenty-eight-day-cycle',
        description: 'once a day for 10 days per 28-day cycle',
      },
      {
        label: '2 times a day for 10 days per 28-day cycle',
        value: 'two-times-a-day-for-ten-days-per-twenty-eight-day-cycle',
        description: '2 times a day for 10 days per 28-day cycle',
      },
      {
        label: '3 times a day for 10 days per 28-day cycle',
        value: 'three-times-a-day-for-ten-days-per-twenty-eight-day-cycle',
        description: '3 times a day for 10 days per 28-day cycle',
      },
      {
        label: 'once a day for 14 days per 21-day cycle',
        value: 'once-a-day-for-fourteen-days-per-twenty-one-day-cycle',
        description: 'once a day for 14 days per 21-day cycle',
      },
      {
        label: '2 times a day for 14 days per 21-day cycle',
        value: 'two-times-a-day-for-fourteen-days-per-twenty-one-day-cycle',
        description: '2 times a day for 14 days per 21-day cycle',
      },
      {
        label: '3 times a day for 14 days per 21-day cycle',
        value: 'three-times-a-day-for-fourteen-days-per-twenty-one-day-cycle',
        description: '3 times a day for 14 days per 21-day cycle',
      },
      {
        label: 'once a day for 21 days per 28-day cycle',
        value: 'once-a-day-for-twenty-one-days-per-twenty-eight-day-cycle',
        description: 'once a day for 21 days per 28-day cycle',
      },
      {
        label: 'once a day from Day 15 to Day 25 of menstrual cycle',
        value: 'once-a-day-from-day-fifteen-to-day-twenty-five-of-menstrual-cycle',
        description: 'once a day from Day 15 to Day 25 of menstrual cycle',
      },
      {
        label: '2 times a day from Day 15 to Day 25 of menstrual cycle',
        value: 'two-times-a-day-from-day-fifteen-to-day-twenty-five-of-menstrual-cycle',
        description: '2 times a day from Day 15 to Day 25 of menstrual cycle',
      },
      {
        label: '3 times a day from Day 15 to Day 25 of menstrual cycle',
        value: 'three-times-a-day-from-day-fifteen-to-day-twenty-five-of-menstrual-cycle',
        description: '3 times a day from Day 15 to Day 25 of menstrual cycle',
      },
      {
        label: 'when required',
        value: 'when-required',
        description: 'when required',
      },
      {
        label: 'once when required',
        value: 'once-when-required',
        description: 'once when required',
      },
      {
        label: 'once every 5 minutes when required',
        value: 'once-every-five-minutes-when-required',
        description: 'every 5 minutes when required',
      },
      {
        label: 'once every 10 minutes when required',
        value: 'once-every-ten-minutes-when-required',
        description: 'every 10 minutes when required',
      },
      {
        label: 'once every 15 minutes when required',
        value: 'once-every-fifteen-minutes-when-required',
        description: 'every 15 minutes when required',
      },
      {
        label: 'once every 30 minutes when required',
        value: 'once-every-thirty-minutes-when-required',
        description: 'every 30 minutes when required',
      },
      {
        label: 'once every hour when required',
        value: 'once-every-hour-when-required',
        description: 'every hour when required',
      },
      {
        label: 'once every 2 hours when required',
        value: 'once-every-two-hour-when-required',
        description: 'every 2 hours when required',
      },
      {
        label: 'once every 3 hours when required',
        value: 'once-every-three-hours-when-required',
        description: 'every 3 hours when required',
      },
      {
        label: 'once every 4 hours when required',
        value: 'once-every-four-hours-when-required',
        description: 'every 4 hours when required',
      },
      {
        label: 'once every 5 hours when required',
        value: 'once-every-five-hours-when-required',
        description: 'every 5 hours when required',
      },
      {
        label: 'once every 6 hours when required',
        value: 'once-every-six-hours-when-required',
        description: 'every 6 hours when required',
      },
      {
        label: 'once every 8 hours when required',
        value: 'once-every-eight-hours-when-required',
        description: 'every 8 hours when required',
      },
      {
        label: 'once every 12 hours when required',
        value: 'once-every-twelve-hours-when-required',
        description: 'every 12 hours when required',
      },
      {
        label: 'once every 48 hours when required',
        value: 'once-every-forty-eight-hours-when-required',
        description: 'every 48 hours when required',
      },
      {
        label: 'once every 72 hours when required',
        value: 'once-every-seventy-two-hours-when-required',
        description: 'every 72 hours when required',
      },
      {
        label: 'once every 2 days when required',
        value: 'once-every-two-days-when-required',
        description: 'every other day when required',
      },
      {
        label: 'once every 2 days in the morning when required',
        value: 'once-every-two-days-in-the-morning-when-required',
        description: 'every other morning when required',
      },
      {
        label: 'once every 2 days in the afternoon when required',
        value: 'once-every-two-days-in-the-afternoon-when-required',
        description: 'every other afternoon when required',
      },
      {
        label: 'once every 2 days at night when required',
        value: 'once-every-two-days-at-night-when-required',
        description: 'every other night when required',
      },
      {
        label: 'once a day when required',
        value: 'once-a-day-when required',
        description: 'once a day when required',
      },
      {
        label: '2 times a day when required',
        value: 'two-times-a-day-when required',
        description: '2 times a day when required',
      },
      {
        label: '3 times a day when required',
        value: 'three-times-a-day-when required',
        description: '3 times a day when required',
      },
      {
        label: '4 times a day when required',
        value: 'four-times-a-day-when required',
        description: '4 times a day when required',
      },
      {
        label: 'once a day in the morning when required',
        value: 'once-a-day-in-the-morning-when required',
        description: 'every morning when required',
      },
      {
        label: 'once a day in the afternoon when required',
        value: 'once-a-day-in-the-afternoon-when required',
        description: 'every afternoon when required',
      },
      {
        label: 'once a day in the evening when required',
        value: 'once-a-day-in-the-evening-when required',
        description: 'every evening when required',
      },
      {
        label: 'once a day at night when required',
        value: 'once-a-day-at-night-when-required',
        description: 'every night when required',
      },
      {
        label: 'once a day at bedtime when required',
        value: 'once-a-day-at-bedtime-when-required',
        description: 'at bedtime when required',
      },
      {
        label: 'once a day in the morning at 6:00am when required',
        value: 'once-a-day-in-the-morning-at-six-am-when-required',
        description: 'every morning at 6am when required',
      },
      {
        label: 'once a day in the morning before food when required',
        value: 'once-a-day-in-the-morning-before-food-when-required',
        description: 'every morning before food when required',
      },
      {
        label: '3 times a day at 8:00am, 2:00pm and at bedtime when required',
        value: 'two-times-a-day-at-eight-am-two-pm-and-at-bedtime-when-required',
        description: '3 times a day at 8am, 2pm and at bedtime when required',
      },
      {
        label: '4 times a day at 8:00am, 1:00pm, 5:00pm and 10:00pm when required',
        value: 'four-times-a-day-at-eight-am-one-pm-five-pm-and-ten-pm-when-required',
        description: '4 times a day at 8am, 1pm, 5pm and 10pm when required',
      },
      {
        label: '2 times a day before food when required',
        value: 'two-times-a-day-before-food-when-required',
        description: '2 times a day before food when required',
      },
      {
        label: '3 times a day before food when required',
        value: 'three-times-a-day-before-food-when-required',
        description: '3 times a day before food when required',
      },
      {
        label: 'once a week when required',
        value: 'once-a-week-when-required',
        description: 'once a week when required',
      },
      {
        label: 'once a month when required',
        value: 'once-a-month-when-required',
        description: 'once a month when required',
      },
      {
        label: 'once a day for 2 days a month when required',
        value: 'once-a-day-for-two-days-a-mouth-when-required',
        description: 'once a day for 2 days a month when required',
      },
      {
        label: 'with food when required',
        value: 'with-food-when-required',
        description: 'with food when required',
      },
      {
        label: 'once during dialysis',
        value: 'once-during-dialysis',
        description: 'once during dialysis',
      },
      {
        label: 'once in the morning for 2 days a week on dialysis days',
        value: 'once-in-the-morning-for-two-days-a-week-on-dialysis-days',
        description: 'in the morning for 2 times a week on dialysis days',
      },
      {
        label: 'once in the morning for 3 days a week on dialysis days',
        value: 'once-in-the-morning-for-three-days-a-week-on-dialysis-days',
        description: 'in the morning for 3 times a week on dialysis days',
      },
      {
        label: 'once at night for 2 days a week on dialysis days',
        value: 'once-at-night-for-two-days-a-week-on-dialysis-days',
        description: 'at night for 2 times a week on dialysis days',
      },
      {
        label: 'once at night for 3 days a week on dialysis days',
        value: 'once-at-night-for-three-days-a-week-on-dialysis-days',
        description: 'at night for 3 times a week on dialysis days',
      },
      {
        label: 'once in the morning for 3 days a week on non-dialysis days',
        value: 'once-in-the-morning-for-three-days-a-week-on-non-dialysis-days',
        description: 'in the morning for 3 times a week on non-dialysis days',
      },
      {
        label: 'once in the morning for 4 days a week on non-dialysis days',
        value: 'once-in-the-morning-for-four-days-a-week-non-dialysis-days',
        description: 'in the morning for 4 times a week on non-dialysis days',
      },
      {
        label: 'once at night for 3 days a week on non-dialysis days',
        value: 'once-at-night-for-three-days-a-week-on-non-dialysis-days',
        description: 'at night for 3 times a week on non-dialysis days',
      },
      {
        label: 'once at night for 4 days a week on non-dialysis days',
        value: 'once-at-night-for-four-days-a-week-on-non-dialysis-days',
        description: 'at night for 4 times a week on non-dialysis days',
      },
      {
        label: '2 times a day for 2 days a week on dialysis days',
        value: 'two-times-a-day-for-two-days-a-week-on-dialysis-days',
        description: '2 times a day for 2 days a week on dialysis days',
      },
      {
        label: '2 times a day for 3 days a week on dialysis days',
        value: 'two-times-a-day-for-three-days-a-week-on-dialysis-days',
        description: '2 times a day for 3 days a week on dialysis days',
      },
      {
        label: '2 times a day for 4 days a week on dialysis days',
        value: 'two-times-a-day-for-four-days-a-week-on-dialysis-days',
        description: '2 times a day for 4 days a week on dialysis days',
      },
      {
        label: '2 times a day for 3 days a week on non-dialysis days',
        value: 'two-times-a-day-for-three-days-a-week-on-non-dialysis-days',
        description: '2 times a day for 3 days a week on non-dialysis days',
      },
      {
        label: '2 times a day for 4 days a week on non-dialysis days',
        value: 'two-times-a-day-for-four-days-a-week-on-non-dialysis-days',
        description: '2 times a day for 4 days a week on non-dialysis days',
      },
      {
        label: '2 times a day for 5 days a week on non-dialysis days',
        value: 'two-times-a-day-for-five-days-a-week-on-non-dialysis-days',
        description: '2 times a day for 5 days a week on non-dialysis days',
      },
      {
        label: '3 times a day for 2 days a week on dialysis days',
        value: 'three-times-a-day-for-two-days-a-week-on-dialysis-days',
        description: '3 times a day for 2 days a week on dialysis days',
      },
      {
        label: '3 times a day for 3 days a week on dialysis days',
        value: 'three-times-a-day-for-three-days-a-week-on-dialysis-days',
        description: '3 times a day for 3 days a week on dialysis days',
      },
      {
        label: '3 times a day for 4 days a week on non-dialysis days',
        value: 'three-times-a-day-for-four-days-a-week-on-non-dialysis-days',
        description: '3 times a day for 4 days a week on non-dialysis days',
      },
      {
        label: '3 times a day for 5 days a week on non-dialysis days',
        value: 'three-times-a-day-for-five-days-a-week-on-non-dialysis-days',
        description: '3 times a day for 5 days a week on non-dialysis days',
      },
      {
        label: '2 times a day for 2 days a week before food, on dialysis days',
        value: 'two-times-a-day-for-two-days-a-week-before-food-on-dialysis-days',
        description: '2 times a day for 2 days a week before food, on dialysis days',
      },
      {
        label: '2 times a day for 3 days a week before food, on dialysis days',
        value: 'two-times-a-day-for-three-days-a-week-before-food-on-dialysis-days',
        description: '2 times a day for 3 days a week before food, on dialysis days',
      },
      {
        label: '2 times a day for 4 days a week before food, on non-dialysis days',
        value: 'two-times-a-day-for-four-days-a-week-before-food-on-non-dialysis-days',
        description: '2 times a day for 4 days a week before food, on non-dialysis days',
      },
      {
        label: '2 times a day for 5 days a week before food, on non-dialysis days',
        value: 'two-times-a-day-for-five-days-a-week-before-food-on-non-dialysis-days',
        description: '2 times a day for 5 days a week before food, on non-dialysis days',
      },
      {
        label: '3 times a day for 2 days a week before food, on dialysis days',
        value: 'three-times-a-day-for-two-days-a-week-before-food-on-dialysis-days',
        description: '3 times a day for 2 days a week before food, on dialysis days',
      },
      {
        value: 'three-times-a-day-for-three-days-a-week-before-food-on-dialysis-days',
        label: '3 times a day for 3 days a week before food, on dialysis days',
        description: '3 times a day for 3 days a week before food, on dialysis days',
      },
      {
        label: '3 times a day for 4 days a week before food, on non-dialysis days',
        value: 'three-times-a-day-for-four-days-a-week-before-food-on-non-dialysis-days',
        description: '3 times a day for 4 days a week before food, on non-dialysis days',
      },
      {
        label: '3 times a day for 5 days a week before food, on non-dialysis days',
        value: 'three-times-a-day-for-five-days-a-week-before-food-on-non-dialysis-days',
        description: '3 times a day for 5 days a week before food, on non-dialysis days',
      },
      {
        label: 'once a week on dialysis days',
        value: 'once-a-week-on-dialysis-days',
        description: 'once a week on dialysis days',
      },
      {
        label: 'once a day for 2 days a week on dialysis days',
        value: 'once-a-day-for-two-days-a-week-on-dialysis-days',
        description: 'once a day for 2 days a week on dialysis days',
      },
      {
        label: 'once a day for 3 days a week on dialysis days',
        value: 'once-a-day-for-three-days-a-week-on-dialysis-days',
        description: 'once a day for 3 days a week on dialysis days',
      },
      {
        label: 'once a day for 4 days a week on dialysis days',
        value: 'once-a-day-for-four-days-a-week-on-dialysis-days',
        description: 'once a day for 4 days a week on dialysis days',
      },
      {
        label: 'once a day for 3 days a week on non-dialysis days',
        value: 'once-a-day-for-three-days-a-week-on-non-dialysis-days',
        description: 'once a day for 3 days a week on non-dialysis days',
      },
      {
        label: 'once a day for 4 days a week on non-dialysis days',
        value: 'once-a-day-for-four-days-a-week-on-non-dialysis-days',
        description: 'once a day for 4 days a week on non-dialysis days',
      },
      {
        label: 'once a day for 5 days a week on non-dialysis days',
        value: 'once-a-day-for-five-days-a-week-on-non-dialysis-days',
        description: 'once a day for 5 days a week on non-dialysis days',
      },
      {
        label: 'once a day for 16 hours',
        value: 'once-a-day-for-sixteen-hours',
        description: 'once a day for 16 hours',
      },
      {
        label: 'once 12 hours before chemotherapy, and once 6 hours before chemotherapy',
        value: 'once-twelve-hours-before-chemotherapy-and-once-six-hours-before-chemotherapy',
        description: 'once 12 hours before chemotherapy and once 6 hours before chemotherapy',
      },
      {
        label: 'once every hour while awake',
        value: 'once-every-hour-while-awake',
        description: 'every hour while awake',
      },
      {
        label: 'once every 2 hours while awake',
        value: 'once-every-two-hour-while-awake',

        description: 'every 2 hours while awake',
      },
      {
        label: 'once every 4 hours while awake',
        value: 'once-every-four-hour-while-awake',
        description: 'every 4 hours while awake',
      },
      {
        label: '4 times a day while awake',
        value: 'four-times-a-day-while-awake',
        description: '4 times a day while awake',
      },
    ],
  },
];
