const relationshipOptions = [
  'Adopted Brother',
  'Adopted Daughter',
  'Adopted Sister',
  'Adopted Son',
  'Adoptive Father',
  'Adoptive Mother',
  'Aunt',
  'Brother',
  'Brother In-Laws',
  'Children',
  'Cousin',
  'Data Not Available',
  'Daughter',
  'Daughter In-Laws',
  'Father',
  'Father In-Laws',
  'Foster Child',
  'Foster Father',
  'Foster Mother',
  'Grandchildren',
  'Granddaughter',
  'Grandfather',
  'Grandmother',
  'Grandparent',
  'Grandson',
  'Guardian',
  'Half-Brother',
  'Half-Sister',
  'Husband',
  'In-Laws',
  'Mother',
  'Mother In-Laws',
  'Nephew',
  'Niece',
  'Other Family Member',
  'Other Non-Family Member',
  'Parent',
  'Siblings',
  'Significant Other',
  'Sister',
  'Sister In-Laws',
  'Son',
  'Son In-Laws',
  'Spouse',
  'Step-Brother',
  'Step-Daughter',
  'Step-Father',
  'Step-Mother',
  'Step-Sister',
  'Step-Son',
  'Uncle',
  'Ward',
  'Wife',
];

export default relationshipOptions;
