// eslint-disable-next-line import/prefer-default-export
export const DISEASE_ITEMS: string[] = [
  'Avian Influenza',
  'Acute Hepatitis A',
  'Acute Hepatitis B',
  'Acute Hepatitis C',
  'Acute Hepatitis E',
  'Botulism',
  'Campylobacteriosis',
  'Chlamydial Genital Infection',
  'Chikungunya Fever',
  'Cholera',
  'Coronavirus Disease 2019 (COVID-19)',
  'Dengue Fever',
  'Diphtheria',
  'Ebola Virus Disease (EVD)',
  'Gonorrhoea',
  'Haemophilus influenzae Type b (Hib) Disease',
  'HIV Infection',
  'Japanese Encephalitis',
  'Legionellosis',
  'Leprosy',
  'Leptospirosis',
  'Malaria',
  'Measles',
  'Melioidosis',
  'Meningococcal Disease',
  'Middle East Respiratory Syndrome Coronavirus Infections (MERS-CoV)',
  'Mpox',
  'Mumps',
  'Murine Typhus',
  'Nipah Virus Infection',
  'Paratyphoid',
  'Pertussis',
  'Pertussis',
  'Pneumococcal Disease (Invasive)',
  'Poliomyelitis',
  'Rabies',
  'Rubella',
  'Salmonellosis',
  'Severe Acute Respiratory Syndrome (SARS)',
  'Syphilis – Congenital',
  'Syphilis – Infectious (Primary/Secondary)',
  'Syphilis – Non-infectious (Latent/Tertiary)',
  'Typhoid',
  'Yellow Fever',
  'Zika Virus Infection',
];
