// eslint-disable-next-line import/prefer-default-export
export const ROLE_LIST_ACTION = {
  ADD_ROLE: 'add-role',
  EDIT_ROLE: 'edit-role',
  DELETE_ROLE: 'delete-role',
};

export const ACCESS_GIVEN_OPTIONS = [
  { label: 'Pricing Output', value: 'Pricing Output' },
  { label: 'Credit Note List', value: 'Credit Note List' },
  { label: 'Deleted Credit Note List', value: 'Deleted Credit Note List' },
  { label: 'Deleted Debit Note List', value: 'Deleted Debit Note List' },
];

export const ROLE_SETTING_FORM_FIELDS = [
  {
    label: 'All Patients',
    group: 'all-patients',
    isEnabled: false,
    fields: [
      {
        label: 'View Patients',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Patients',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Patients',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Patients',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: ' Patient Lists',
    group: 'patient-list',
    isEnabled: false,
    fields: [
      {
        label: 'View Patient Group',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Patient Group',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Patient Group',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Patient Group',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Prescriptions',
    group: 'prescription',
    isEnabled: false,
    fields: [
      {
        label: 'View Prescriptions',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Prescriptions',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Prescriptions',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Prescriptions',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Dispenses',
    group: 'dispense',
    isEnabled: false,
    fields: [
      {
        label: 'View Dispenses',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Dispenses',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Dispenses',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Dispenses',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Invoices',
    group: 'invoice',
    isEnabled: false,
    fields: [
      {
        label: 'View Invoices',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Invoices',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Access Given',
        name: 'add_access_given',
        type: 'select',
        checked: undefined,
        value: undefined,
      },
      {
        label: 'Edit Invoices',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Invoices',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Access Given',
        name: 'delete_access_given',
        type: 'select',
        checked: undefined,
        value: undefined,
      },
    ],
  },
  {
    label: 'Payment',
    group: 'payment',
    isEnabled: false,
    fields: [
      {
        label: 'View Payment',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Payment',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Payment',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Payment',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Appointments',
    group: 'appointment',
    isEnabled: false,
    fields: [
      {
        label: 'View Appointments',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Appointments',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Appointments',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Appointments',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Queue',
    group: 'queue',
    isEnabled: false,
    fields: [
      {
        label: 'View Queue',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Queue',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Queue',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Queue',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Medical Record',
    group: 'medical-record',
    isEnabled: false,
    fields: [
      {
        label: 'View Medical Records',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Medical Records',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Medical Records',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Medical Records',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Users',
    group: 'users',
    isEnabled: false,
    fields: [
      {
        label: 'View Medical Users',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Medical Users',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Medical Users',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Medical Users',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
  {
    label: 'Two-Factor Authentication (2FA)',
    group: '2fa',
    isEnabled: false,
    value: '',
    fields: [
      {
        label: 'SMS',
        name: '2fa',
        type: 'radio',
        checked: undefined,
        value: 'sms',
      },
      {
        label: 'Email',
        name: '2fa',
        type: 'radio',
        checked: undefined,
        value: 'email',
      },
    ],
  },
  {
    label: 'Role',
    group: 'role',
    isEnabled: false,
    fields: [
      {
        label: 'View Role',
        name: 'read',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Add Role',
        name: 'create',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Edit Role',
        name: 'update',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
      {
        label: 'Delete Role',
        name: 'delete',
        type: 'checkbox',
        checked: false,
        value: undefined,
      },
    ],
  },
];
