name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          cache: yarn

      - name: Install Node.js dependencies
        run: yarn install --immutable --inline-builds

      - name: Run linters
        run: |
          yarn workspace admin lint
          yarn workspace clinic lint
          yarn workspace hward lint
          yarn workspace report-portal lint
          yarn workspace share-components lint
