import { QueueScheduledAppointmentTypes } from 'modules/queue/components/QueueScheduleAppointment/queue-scheduled-appointment-types';

export const appointmentToday: QueueScheduledAppointmentTypes[] = [
  {
    bookingSource: 'PHONE',
    startDate: 'Thursday, March 23, 2023 8:00:00 AM',
    endDate: 'Thursday, March 23, 2023 8:15:00 AM',
    duration: '15_MINUTES',
    patientType: 'new',
    patientId: '031459',
    patientName: 'Ika Septia Puteri Chandra',
    patientEmail: 'test@gmail.com',
    countryCode: 0,
    phoneNumber: '(+65) 8760 2112',
    idType: 0,
    idNumber: '111111',
    doctor: 'Dr Fillah Elizabeth',
    room: 1,
    reason: 'GENERAL',
    detail: 'Line reserved for comment',
    isSendNotification: true,
    sendVia: 1,
    remiderType: 1,
    status: 'DRAFT',
  },
  {
    bookingSource: 'PHONE',
    startDate: 'Thursday, March 23, 2023 10:00:00 AM',
    endDate: 'Thursday, March 23, 2023 10:30:00 AM',
    duration: '30_MINUTES',
    patientType: 'new',
    patientId: '031460',
    patientName: 'Ika Septia Puteri Chandra',
    patientEmail: 'test@gmail.com',
    countryCode: 0,
    phoneNumber: '(+65) 8760 2112',
    idType: 0,
    idNumber: '111111',
    doctor: 'Dr Harbinder Kaur',
    room: 1,
    reason: 'FU_CONSULT',
    detail: 'Line reserved for comment',
    isSendNotification: true,
    sendVia: 1,
    remiderType: 1,
    status: 'DRAFT',
  },
  {
    bookingSource: 'PHONE',
    startDate: 'Thursday, March 23, 2023 1:00:00 PM',
    endDate: 'Thursday, March 23, 2023 2:00:00 PM',
    duration: '1_HOUR',
    patientType: 'new',
    patientId: '031461',
    patientName: 'Ika Septia Puteri Chandra',
    patientEmail: 'test@gmail.com',
    countryCode: 0,
    phoneNumber: '(+65) 8760 2112',
    idType: 0,
    idNumber: '111111',
    doctor: 'Dr William',
    room: 1,
    reason: 'GENERAL_X_RAY',
    detail: 'Line reserved for comment',
    isSendNotification: true,
    sendVia: 1,
    remiderType: 1,
    status: 'DRAFT',
  },
];
